steps:
  - template: ../steps/install-nodejs.yml
  - template: ../steps/install-dependencies.yml
    parameters:
      flags: --production=true # should *only* check Node.js engines on non-dev dependencies
