---
language: node_js
node_js:
  - 4
  - stable
cache:
  yarn: true
  directories:
  - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  allow_failures:
    - env: NODE_ENV=production
  fast_finish: true
install:
  - yarn install --production=false
before_script:
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
  - AST_COMPARE=1 yarn test -- --runInBand
  # A basic test to ensure prettier runs without devDependencies
  - rm -rf node_modules
  - yarn install --production=true
  - ./bin/prettier.js ./bin/prettier.js >/dev/null
#deploy:
#  provider: script
#  script: website/deploy.sh
#  skip_cleanup: true  
#  on:
#    branch: master
#    node: stable
