---
language: node_js
node_js:
  - 4
  - stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  fast_finish: true
before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url $TS_ORG.testspace.com
install:
  - NODE_ENV=development yarn install
before_script:
  - yarn check-deps
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
  - yarn lint-docs
  - if [ "${NODE_ENV}" = "production" ]; then yarn test:dist; fi
  - if [ "${NODE_ENV}" = "development" ]; then AST_COMPARE=1 yarn test -- --runInBand; fi
  - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
after_script:
  - testspace [node-${TRAVIS_NODE_VERSION}/${NODE_ENV}]junit.xml{.}
branches:
  only:
    - master
    - add-test-reporting
