---
language: node_js
node_js:
  - 4
  - stable
cache:
  yarn: true
  directories:
  - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  fast_finish: true
install:
  - NODE_ENV=development yarn install
before_install:
  - curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 2.7.11
  - pyenv install 3.6.3
  - pyenv global 2.7.11 3.6.3
before_script:
  - yarn check-deps
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
  - yarn lint-docs
  - AST_COMPARE=1 yarn test -- --runInBand
  - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
