trigger:
- master
- releases/*

jobs:

# Test production bundle on Linux using Node 4
- job: prod_linux_node_4
  displayName: Test production bundle (Linux, node 4)
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Production Bundle Node 4 (Linux):
        node.version: '4.x'
      Production Bundle Node 9 (Linux):
        node.version: '9.x'
  steps:
  - template: azure-pipelines/production-bundle.yml

# Build and test on Windows
- job: Test(Windows)
  displayName: Run tests using Node 8 (Windows)
  pool:
    vmImage: vs2017-win2016
  variables:
    node_version: 8.x
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Build and test on macOS
- job: Test(macOS)
  displayName: Run tests using Node 8 (macOS)
  pool:
    vmImage: macos-10.13
  variables:
    node_version: 8.x
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Build and test on Linux
- job: 'Test(Linux)'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Run tests using Node 8 (Linux):
        node.version: '8.x'
      Production Bundle Node 11 (Linux):
        node.version: '11.x'
  variables:
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Lint checks on Linux
- job: lint_linux
  displayName: Lint (Linux)
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'yarn install'

  - script: yarn lint
    displayName: 'Lint code'

  - script: yarn lint-docs
    displayName: 'Lint docs'