trigger:
- master
- releases/*

jobs:

# Test production bundle on Linux using Node 4
- job: Prod_Linux
  displayName: Test production bundle on Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node4:
        node_version: '4.x'
      Node9:
        node_version: '9.x'
  steps:
  - template: azure-pipelines/production-bundle.yml

# Build and test on Windows
- job: Test_Windows
  displayName: Tests on Windows Node8
  pool:
    vmImage: vs2017-win2016
  variables:
    node_version: 8.x
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Build and test on macOS
- job: Test_macOS
  displayName: Tests on macOS Node8
  pool:
    vmImage: macos-10.13
  variables:
    node_version: 8.x
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Build and test on Linux
- job: Test_Linux
  displayName: Tests on Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node8:
        node_version: '8.x'
      Node11:
        node_version: '11.x'
  variables:
    report_summaries: true
  steps:
  - template: azure-pipelines/run-tests.yml

# Lint checks on Linux
- job: Lint_linux
  displayName: Lint (Linux)
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'yarn install'

  - script: yarn lint
    displayName: 'Lint code'

  - script: yarn lint-docs
    displayName: 'Lint docs'