blank_issues_enabled: true
contact_links:
  - name: 🤔 Support question
    url: https://stackoverflow.com/questions/ask?tags=prettier
    about: Issues are dedicated to development purposes, if you have questions, please use Stack Overflow.
