name: "PREPARE_ACTION"
description: "Checkout repository, install Node.js, install dependencies"
author: fisker
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Setup Node.js
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{ matrix.node }}
        cache: "yarn"

    - name: Install Dependencies
      run: yarn install --immutable
