name: Check Sizes

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-sizes:
    name: Check Sizes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          cache: "yarn"

      - name: Check Sizes
        uses: pkg-size/action@v1.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          build-command: yarn build --clean
          display-size: uncompressed
