name: Dev

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node:
          - "13"
          - "12"
          - "10"
        exclude:
          - os: "macos-latest"
            node: "13"
          - os: "macos-latest"
            node: "12"
          - os: "windows-latest"
            node: "13"
          - os: "windows-latest"
            node: "12"
        include:
          # only enable coverage on the fastest job
          - os: "macos-latest"
            node: "10"
            ENABLE_CODE_COVERAGE: "true"
    env:
      ENABLE_CODE_COVERAGE: ${{ matrix.ENABLE_CODE_COVERAGE }}
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Upload Coverage To Codecov
        uses: codecov/codecov-action@v1
        if: matrix.ENABLE_CODE_COVERAGE
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/cobertura-coverage.xml
          fail_ci_if_error: true

      - name: Upload Coverage To Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.ENABLE_CODE_COVERAGE
        with:
          github-token: ${{ secrets.github_token }}
