name: Lint

on:
  push:
    branches:
      - master
      - patch-release
  pull_request:

jobs:
  cleanup:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Dependencies
        run: yarn lint:deps

      - name: Check JSDoc Types
        run: yarn lint:typecheck

      - name: Lint ESLint
        run: yarn lint:eslint

      - name: Lint Prettier
        run: yarn lint:prettier

      - name: Spellcheck
        run: yarn lint:spellcheck

      - name: Lint Changelog
        run: yarn lint:changelog

      - name: Check Lock File Changes
        run: yarn && echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed during lint."
