steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: npm install -g yarn
  displayName: 'Get yarn'

- script: yarn install
  displayName: 'yarn install'

- script: yarn check-deps
  displayName: 'Check dependencies'

- script: yarn build
  displayName: 'Build'

- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Use Node.js $(node_version)'

- script: npm install -g yarn@1.5
  displayName: 'Get yarn compatible with node 4'
  condition: eq(variables['node_version'], '4.x')

- script: node ./scripts/test-dist.js
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/junit.xml'
  condition: and(variables['report_summaries'], succeededOrFailed())